[helpers]

[nvim.files]
nvim = "~/AppData/Local/nvim"

[alacritty.files]
alacritty = "~/.config/alacritty"

[starship.files]
starship = "~/.config/starship.toml"

[glzr.files]
glzr = "~/.glzr"

[settings]
default_target_type = "automatic"
